export type { EmailConfig, EmailProvider, EmailProviderConfig, EmailProviders, EmailSendResult, EmailTemplate, SendEmailOptions, SendMailOptions, TotpEmailData } from './@types/email.types';
export { defaultEmailConfig } from './email.config';
export { emailContext } from './email.context';
export { createEmailProvider, getEmailProviderNames, getProviderConfig, getSupportedProviders, isValidProvider } from './email-provider';
export { EmailSchema } from './email-validator';
export { MockEmailProvider } from './providers/local-dev';
export { MailChannelsEmailProvider } from './providers/mailchannels';
export { ResendEmailProvider } from './providers/resend';
export { TestMockEmailProvider } from './providers/test-mock';
export { createTotpTemplate } from './templates/auth-totp';
export { createMinimalTemplate } from './templates/minimal-template';
export { createMockTemplate } from './templates/mock-template';
