/**
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * Auto-generated Tailwind CSS utility styles map for email components at: 2025-11-03T14:14:42.950Z
 *
 *   - Template files scanned: 4
 *   - Unique classes found: 37
 *   - Static styles mapped: 36
 *   - Dynamic patterns: 2
 */

import type { TailwindStylesMap } from '@ycore/componentry/email/server';
import type { CSSProperties } from 'react';

export const TAILWIND_TO_CSS_MAP: Record<string, Partial<CSSProperties>> = {
  'm-0': { margin: '0rem' },
  'm-3': { margin: '0.75rem' },
  'm-4': { margin: '1rem' },
  'm-5': { margin: '1.25rem' },
  'mx-2': { marginInline: '0.5rem' },
  'mx-5': { marginInline: '1.25rem' },
  'mx-auto': { marginInline: 'auto' },
  'my-5': { marginBlock: '1.25rem' },
  'max-w-2xl': { maxWidth: '42rem' },
  'max-w-md': { maxWidth: '28rem' },
  'rounded-2xl': { borderRadius: '1rem' },
  'rounded-lg': { borderRadius: '0.625rem' },
  'border-2': { borderStyle: 'var(--tw-border-style)', borderWidth: '2px' },
  'border-border': { borderColor: 'oklch(70.7% 0.022 261.325)' },
  'bg-muted': { backgroundColor: 'oklch(87.2% 0.01 258.338)' },
  'bg-white': { backgroundColor: '#fff' },
  'p-3': { padding: '0.75rem' },
  'p-5': { padding: '1.25rem' },
  'px-5': { paddingInline: '1.25rem' },
  'py-5': { paddingBlock: '1.25rem' },
  'pt-10': { paddingTop: '2.5rem' },
  'pb-5': { paddingBottom: '1.25rem' },
  'text-center': { textAlign: 'center' },
  'text-left': { textAlign: 'left' },
  'font-sans': { fontFamily: "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol',\n    'Noto Color Emoji'" },
  'text-3xl': { fontSize: '1.875rem', lineHeight: 'var(--text-3xl--line-height)' },
  'text-sm': { fontSize: '0.875rem', lineHeight: 'var(--text-sm--line-height)' },
  'leading-relaxed': { lineHeight: '1.625' },
  'font-bold': { fontWeight: '700' },
  'text-destructive': { color: 'oklch(50.5% 0.213 27.518)' },
  'text-foreground': { color: 'oklch(27.8% 0.033 256.848)' },
  'text-muted-foreground': { color: 'oklch(55.1% 0.027 264.364)' },
  italic: { fontStyle: 'italic' },
  'no-underline': { textDecorationLine: 'none' },
  underline: { textDecorationLine: 'underline' },
  dark: { color: 'color-mix(in lab, red, red)) {\n    & {\n      --border: color-mix(in oklab, oklch(96.7% 0.003 264.542) 10%, transparent)' },
};

export const DYNAMIC_UTILITY_PATTERNS = [
  {
    regex: /^text-\[(.+?)\]$/,
    converter: (matches: RegExpMatchArray) => ({ fontSize: matches[1] }),
  },
  {
    regex: /^tracking-\[(.+?)\]$/,
    converter: (matches: RegExpMatchArray) => ({ letterSpacing: matches[1] }),
  },
];

export const TEMPLATE_STYLES_MAP: TailwindStylesMap = {
  cssMap: TAILWIND_TO_CSS_MAP,
  dynamicPatterns: DYNAMIC_UTILITY_PATTERNS,
};
