/**
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * Auto-generated Tailwind CSS utility styles map for email components at: 2025-11-03T14:14:42.961Z
 *
 *   - Template files scanned: 2
 *   - Unique classes found: 23
 *   - Static styles mapped: 24
 *   - Dynamic patterns: 0
 */

import type { TailwindStylesMap } from '@ycore/componentry/email/server';
import type { CSSProperties } from 'react';

export const TAILWIND_TO_CSS_MAP: Record<string, Partial<CSSProperties>> = {
  'mx-auto': { marginInline: 'auto' },
  'my-5': { marginBlock: '1.25rem' },
  'max-w-2xl': { maxWidth: '42rem' },
  rounded: { borderRadius: '0.25rem' },
  'border-b': { borderBottomStyle: 'var(--tw-border-style)', borderBottomWidth: '1px' },
  'border-l-4': { borderLeftStyle: 'var(--tw-border-style)', borderLeftWidth: '4px' },
  'border-blue-500': { borderColor: 'oklch(62.3% 0.214 259.815)' },
  'border-border': { borderColor: 'oklch(70.7% 0.022 261.325)' },
  'bg-muted': { backgroundColor: 'oklch(87.2% 0.01 258.338)' },
  'bg-white': { backgroundColor: '#fff' },
  'p-4': { padding: '1rem' },
  'p-5': { padding: '1.25rem' },
  'px-5': { paddingInline: '1.25rem' },
  'py-5': { paddingBlock: '1.25rem' },
  'py-8': { paddingBlock: '2rem' },
  'pt-10': { paddingTop: '2.5rem' },
  'pb-5': { paddingBottom: '1.25rem' },
  'text-center': { textAlign: 'center' },
  'font-sans': { fontFamily: "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol',\n    'Noto Color Emoji'" },
  'text-sm': { fontSize: '0.875rem', lineHeight: 'var(--text-sm--line-height)' },
  'text-foreground': { color: 'oklch(27.8% 0.033 256.848)' },
  'text-gray-900': { color: 'oklch(21% 0.034 264.665)' },
  'text-muted-foreground': { color: 'oklch(55.1% 0.027 264.364)' },
  dark: { color: 'color-mix(in lab, red, red)) {\n    & {\n      --border: color-mix(in oklab, oklch(96.7% 0.003 264.542) 10%, transparent)' },
};

export const DYNAMIC_UTILITY_PATTERNS = [
  // No dynamic patterns detected
];

export const TEMPLATE_STYLES_MAP: TailwindStylesMap = {
  cssMap: TAILWIND_TO_CSS_MAP,
  dynamicPatterns: DYNAMIC_UTILITY_PATTERNS,
};
